[workspace]
members = [
  "auction/program",
  "auction/cli",
  "metaplex/program",
  "metaplex/test",
  "token-vault/program",
  "token-vault/test",
  "token-metadata/program",
  "token-metadata/test"
]
exclude = [
]
